<?php

use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Dynamic Tenant Routes
|--------------------------------------------------------------------------
|
| These routes are automatically generated by the PageTemplateService
| when custom navigation items are created.
|
*/

// Auto-generated route for: TestPage
Route::get('/testpage', function () {
    return Inertia::render('Testpage/Testpage', [
        'pageTitle' => 'TestPage'
    ]);
})->middleware('auth')->name('tenant.testpage');
// Auto-generated route for: Bogdan
Route::get('/bogdan', function () {
    $user = auth()->user();
    $tenant = $user->tenant;
    
    return Inertia::render('Bogdan/Bogdan', [
        'pageTitle' => 'Bogdan',
        'stats' => [
            'tenant_id' => $user->tenant_id,
            'tenant_name' => $tenant?->name ?? 'Your Organization',
        ],
    ]);
})->middleware('auth')->name('tenant.bogdan');