<?php

use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Dynamic Tenant Routes
|--------------------------------------------------------------------------
|
| These routes are automatically generated by the PageTemplateService
| when custom navigation items are created.
|
*/

// Auto-generated route for: TestPage
Route::get('/testpage', function () {
    return Inertia::render('Testpage/Testpage', [
        'pageTitle' => 'TestPage'
    ]);
})->middleware('auth')->name('tenant.testpage');