<?php

use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Dynamic Tenant Routes
|--------------------------------------------------------------------------
|
| These routes are automatically generated by the PageTemplateService
| when custom navigation items are created.
|
*/

// Auto-generated route for: Inventory Management
Route::get('/inventory_management', function () {
    $user = auth()->user();
    $tenant = $user->tenant;
    
    return Inertia::render('InventoryManagement/InventoryManagement', [
        'pageTitle' => 'Inventory Management',
        'stats' => [
            'tenant_id' => $user->tenant_id,
            'tenant_name' => $tenant?->name ?? 'Your Organization',
        ],
    ]);
})->middleware('auth')->name('tenant.inventory_management');
// Auto-generated route for: CustomDashboard
Route::get('/customdashboard', function () {
    $user = auth()->user();
    $tenant = $user->tenant;
    
    return Inertia::render('Customdashboard/Customdashboard', [
        'pageTitle' => 'CustomDashboard',
        'stats' => [
            'tenant_id' => $user->tenant_id,
            'tenant_name' => $tenant?->name ?? 'Your Organization',
        ],
    ]);
})->middleware('auth')->name('tenant.customdashboard');
// Auto-generated route for: CustomDashboards
Route::get('/customdashboards', function () {
    $user = auth()->user();
    $tenant = $user->tenant;
    
    return Inertia::render('Customdashboards/Customdashboards', [
        'pageTitle' => 'CustomDashboards',
        'stats' => [
            'tenant_id' => $user->tenant_id,
            'tenant_name' => $tenant?->name ?? 'Your Organization',
        ],
    ]);
})->middleware('auth')->name('tenant.customdashboards');
// Auto-generated route for: CustomDashboardData
Route::get('/customdashboarddata', function () {
    $user = auth()->user();
    $tenant = $user->tenant;
    
    return Inertia::render('Customdashboarddata/Customdashboarddata', [
        'pageTitle' => 'CustomDashboardData',
        'stats' => [
            'tenant_id' => $user->tenant_id,
            'tenant_name' => $tenant?->name ?? 'Your Organization',
        ],
    ]);
})->middleware('auth')->name('tenant.customdashboarddata');
// Auto-generated route for: Sales Dashboard
Route::get('/sales_dashboard', function () {
    $user = auth()->user();
    $tenant = $user->tenant;
    
    return Inertia::render('SalesDashboard/SalesDashboard', [
        'pageTitle' => 'Sales Dashboard',
        'stats' => [
            'tenant_id' => $user->tenant_id,
            'tenant_name' => $tenant?->name ?? 'Your Organization',
        ],
    ]);
})->middleware('auth')->name('tenant.sales_dashboard');
// Auto-generated route for: User Directory
Route::get('/user_directory', function () {
    $user = auth()->user();
    $tenant = $user->tenant;
    
    return Inertia::render('UserDirectory/UserDirectory', [
        'pageTitle' => 'User Directory',
        'stats' => [
            'tenant_id' => $user->tenant_id,
            'tenant_name' => $tenant?->name ?? 'Your Organization',
        ],
    ]);
})->middleware('auth')->name('tenant.user_directory');
// Auto-generated route for: TestPage
Route::get('/testpage', function () {
    return Inertia::render('Testpage/Testpage', [
        'pageTitle' => 'TestPage'
    ]);
})->middleware('auth')->name('tenant.testpage');